server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/

logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{traceId:-},%X{spanId:-}] ${LOG_LEVEL_PATTERN:-%5p} %m%n"
              
spring:
  output:
    ansi:
      enabled: always
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: user-service
        uri: lb://user-service
        predicates:
        - Path=/user/**
        filters:
        - RewritePath=/user/(?<path>.*), /$\{path}
      - id: ride-service
        uri: lb://ride-service
        predicates:
        - Path=/ride/**
        filters:
        - RewritePath=/ride/(?<path>.*), /$\{path}
      - id: booking-service
        uri: lb://booking-service
        predicates:
        - Path=/booking/**
        filters:
        - RewritePath=/booking/(?<path>.*), /$\{path}
      - id: openapi
        uri: http://localhost:${server.port}
        predicates:
        - Path=/v3/api-docs/**
        filters:
        - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs

springdoc:
  swagger-ui:
    urls:
      - name: user
        url: /v3/api-docs/user
      - name: ride
        url: /v3/api-docs/ride
      - name: booking
        url: /v3/api-docs/booking

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans