version: "3.7"
services:
  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    extra_hosts: [ 'host.docker.internal:host-gateway' ]
    ports:
      - "9411:9411"
  config-service:
    build:
      context: ./config-service
      dockerfile: Dockerfile
    ports:
      - "8088:8088"
    healthcheck:
      test: curl --fail http://localhost:8088/user/docker  || exit 1
      interval: 5s
      timeout: 2s
      retries: 3
  discovery-service:
    build:
      context: ./discovery-service
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    depends_on:
      config-service:
        condition: service_healthy
    links:
      - config-service
    healthcheck:
      test: curl --fail http://localhost:8761/eureka/v2/apps || exit 1
      interval: 4s
      timeout: 2s
      retries: 3
    environment:
      SPRING_PROFILES_ACTIVE: docker
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "8080"
    depends_on:
      discovery-service:
        condition: service_healthy
    links:
      - config-service
      - discovery-service
      - zipkin
    environment:
      SPRING_PROFILES_ACTIVE: docker
  ride-service:
    build:
      context: ./ride-service
      dockerfile: Dockerfile
    ports:
      - "8080"
    depends_on:
      discovery-service:
        condition: service_healthy
    links:
      - config-service
      - discovery-service
      - user-service
      - zipkin
    environment:
      SPRING_PROFILES_ACTIVE: docker
  booking-service:
    build:
      context: ./booking-service
      dockerfile: Dockerfile
    ports:
      - "8080"
    depends_on:
      discovery-service:
        condition: service_healthy
    links:
      - config-service
      - discovery-service
      - user-service
      - ride-service
      - zipkin
    environment:
      SPRING_PROFILES_ACTIVE: docker
  gateway-service:
    build:
      context: ./gateway-service
      dockerfile: Dockerfile
    ports:
      - "8060:8060"
    depends_on:
      discovery-service:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
    links:
      - config-service
      - discovery-service
      - user-service
      - ride-service
      - booking-service
      - zipkin